### ISSUE TITLE
v1.9 - fails to start - curl: (23) Failed writing body (0 != 676)

### ISSUE THREAD

**Issue by djschny** [kubernetes-sigs/kubeadm-dind-cluster#104]
Linux lab-client 4.13.0-1011-gcp #15-Ubuntu SMP Mon Feb 12 16:29:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```
$ ./dind-cluster-v1.9.sh up
WARNING: No swap limit support
WARNING: No swap limit support
WARNING: No swap limit support
WARNING: No swap limit support
* Making sure DIND image is up to date 
v1.9: Pulling from mirantis/kubeadm-dind-cluster
952132ac251a: Already exists 
82659f8f1b76: Pull complete 
c19118ca682d: Pull complete 
8296858250fe: Pull complete 
24e0251a0e2c: Pull complete 
2545d638d973: Pull complete 
e0b45d7ea196: Pull complete 
8d7d40f3e602: Pull complete 
216f5a138844: Pull complete 
c71de27d6b60: Pull complete 
71d6ee42e600: Pull complete 
2ed1884f27bd: Pull complete 
dc9263aecb3c: Pull complete 
5ca861edd39a: Pull complete 
a4ac708b644e: Pull complete 
95fee8b23e4d: Pull complete 
6945885fa46e: Pull complete 
4a5f1c282163: Pull complete 
c25f5d0fc036: Pull complete 
5afd8ce0cf11: Pull complete 
2434cb1d3af0: Pull complete 
de6b6099015b: Pull complete 
868e88939d4d: Pull complete 
c0f5fda949d0: Pull complete 
1e623fe7630f: Pull complete 
Digest: sha256:66f8da84e0d9035d308a57fe537472ddabeb14e498b9de51cd08527e7881eb08
Status: Downloaded newer image for mirantis/kubeadm-dind-cluster:v1.9
curl: (23) Failed writing body (0 != 676)
```

**Comment by lukaszo** [comment]
Looks like a random network error. Is it still failing?

**Comment by djschny** [comment]
Yes it will happen consistently. However I did notice it only appears to happen if the `v1.7` script is run and then a `clean` is done and then the `v1.9` script is run.

**Comment by mayrbenjamin92** [comment]
I have the same issue running ``v1.9``:

* Making sure DIND image is up to date 
v1.9: Pulling from mirantis/kubeadm-dind-cluster
952132ac251a: Pull complete 
82659f8f1b76: Pull complete 
c19118ca682d: Pull complete 
8296858250fe: Pull complete 
24e0251a0e2c: Pull complete 
2545d638d973: Pull complete 
e0b45d7ea196: Pull complete 
8d7d40f3e602: Pull complete 
216f5a138844: Pull complete 
c71de27d6b60: Pull complete 
b6dede24b1b9: Pull complete 
ac626bf35c3c: Pull complete 
59e2b2e31d04: Pull complete 
1ec1ae311043: Pull complete 
68a40e508e86: Pull complete 
773430d6307f: Pull complete 
fb54135e2d3b: Pull complete 
96c60d68108c: Pull complete 
2d4dfc9f416f: Pull complete 
b125451bcd5a: Pull complete 
789cd944eef5: Pull complete 
f6b42c60add5: Pull complete 
8784a5c218c1: Pull complete 
c16d1274c371: Pull complete 
80035de2ba66: Pull complete 
Digest: sha256:84c288ce56fa1e311a277c1597b262a00f4b9db8000a99a78cd669d951b0e7a6
Status: Downloaded newer image for mirantis/kubeadm-dind-cluster:v1.9
curl: (23) Failed writing body (0 != 547)
