### ISSUE TITLE
How to use insecure registries

### ISSUE THREAD

**Issue by jevin36** [kubernetes-sigs/kubeadm-dind-cluster#119]
Hi can you give me an example how I can configure the use of insecure registries?
Regards

**Comment by pigmej** [comment]
@jevin36 just set `DIND_INSECURE_REGISTRIES="[\"0.0.0.0/0\"]"` as env variable for example
it's json list so any configuration from https://docs.docker.com/registry/insecure/ will work

**Comment by pigmej** [comment]
`dind::init` is called from `dind::up`. How do you actually set the variable? Have you exported it?

**Comment by jevin36** [comment]
Hi @pigmej ,
yes I did. I don't see that "init" is called from "up", so I temporary added static invocations
    dind::custom-docker-opts kube-master
    dind::custom-docker-opts kube-node-1
    dind::custom-docker-opts kube-node-2  

to the "up" method. Then it works.

**Comment by pigmej** [comment]
https://github.com/Mirantis/kubeadm-dind-cluster/blob/master/dind-cluster.sh#L970

There is the invocation of `dind::init` in `dind::up`

**Comment by phcollignon** [comment]
I tested by setting the DIND_INSECURE_REGISTRIES with dind-cluser-v1.9.sh and it worked out of the box.
I just had to clean all to recreate new images.

**Comment by pigmej** [comment]
@jevin36 any update from your side?

**Comment by TrentonAdams** [comment]
I get the same error as filed at issue 288.  They trigger the same code block.

```
export DIND_INSECURE_REGISTRIES="[\"0.0.0.0/0\"]"
$ dind-cluster-v1.13.sh up
WARNING: No swap limit support
WARNING: No swap limit support
WARNING: No swap limit support
WARNING: No swap limit support
* Making sure DIND image is up to date 
sha256:0fcb655948a1fa20f5a2100983755edc8f0d763248bda217b3454d82d5cd3be4: Pulling from mirantis/kubeadm-dind-cluster
Digest: sha256:0fcb655948a1fa20f5a2100983755edc8f0d763248bda217b3454d82d5cd3be4
Status: Image is up to date for mirantis/kubeadm-dind-cluster@sha256:0fcb655948a1fa20f5a2100983755edc8f0d763248bda217b3454d82d5cd3be4
* Starting DIND container: kube-master
* + Setting up insecure-registries on kube-master 
Job for docker.service canceled.
```

**Comment by TrentonAdams** [comment]
Also, if I replace that line with a `sudo systemctl restart docker` from the host machine, it fails with...
```
$ dind-cluster-v1.13.sh up
WARNING: No swap limit support
WARNING: No swap limit support
WARNING: No swap limit support
WARNING: No swap limit support
* Making sure DIND image is up to date 
sha256:0fcb655948a1fa20f5a2100983755edc8f0d763248bda217b3454d82d5cd3be4: Pulling from mirantis/kubeadm-dind-cluster
Digest: sha256:0fcb655948a1fa20f5a2100983755edc8f0d763248bda217b3454d82d5cd3be4
Status: Image is up to date for mirantis/kubeadm-dind-cluster@sha256:0fcb655948a1fa20f5a2100983755edc8f0d763248bda217b3454d82d5cd3be4
* Starting DIND container: kube-master
* + Setting up insecure-registries on kube-master 
Error response from daemon: Container 31a7af62954400e74448e284738c422e2f7b06ff96c6dea5bcde97120c77b4eb is not running
```

**Comment by morningspace** [comment]
The` DIND_INSECURE_REGISTRIES` option works fine w/ latest version of the scripts that I tested,
also, `Job for docker.service canceled.` is a known issue which I believe has been fixed w/ the new released pre-configured scripts, e.g. https://github.com/kubernetes-sigs/kubeadm-dind-cluster/releases/download/v0.2.0/dind-cluster-v1.14.sh.
