### ISSUE TITLE
persistent volumes doesn't work

### ISSUE THREAD

**Issue by mikeburon** [kubernetes-sigs/kubeadm-dind-cluster#122]
Persistent volumes in local doesn't work

**Comment by ivan4th** [comment]
Do you mean local persistent volumes? I.e. same as in #139

**Comment by imriss** [comment]
This example uses `kubeadm-dind-cluster` with local persistent volume on the host: [p1-local-persistent-volume-host](https://github.com/imriss/kubernetes_factory/tree/master/p1-local-persistent-volume-host)
