### ISSUE TITLE
Error bringing up kube-dns and kubernetes-dashboard

### ISSUE THREAD

**Issue by mail2fish** [kubernetes-sigs/kubeadm-dind-cluster#126]
The error message like this. 

* Bringing up kube-dns and kubernetes-dashboard
deployment "kube-dns" scaled
deployment "kubernetes-dashboard" scaled
............................................................................................................................................................................
...........................
Error bringing up kube-dns and kubernetes-dashboard

The environment that I am working at is  CentOS Linux release 7.5.1804 (Core)

docker version
Client:
 Version:      17.03.2-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.2-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   f5ec1e2
 Built:        Tue Jun 27 02:21:36 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Comment by entropyie** [comment]
I am also seeing this issue.
If I do a `docker images` inside the kube-master, I can see multiple images including kube-dns of version 1.14.5 are **not** present (other images are, such as kube-dns 1.7). If I connect the Host OS to the internet they can be downloaded externally, but I would very much prefer not to do that.

Host OS Docker Server version 1.13.1
I am also running Centos 7.

**Comment by ivan4th** [comment]
Could you please do `./dind-cluster-....sh dump` in this state and post the result?

**Comment by entropyie** [comment]
@ivan4th I have since moved from building k8s 1.8.x to 1.10.x and no longer see this particular issue (sorry, I don't have time to switch back to 1.8 now).
I imagine the dns/dashboard yaml files pointed to in the 1.8 script are not tagged to 1.8 and are pulling in newer dependencies.

Since moving to 1.10 the images are present but there are other problems which I will discuss separately :)

**Comment by ivan4th** [comment]
@mail2fish do you still have the issue? If so, could you please dump the cluster state `./dind-cluster-....sh dump` and post the result?

**Comment by mail2fish** [comment]
@ivan4th Hi, I still got that problem. The dump file is so big, so I compress it by gzip.

[dnd_dump.txt.gz](https://github.com/kubernetes-sigs/kubeadm-dind-cluster/files/2060923/dnd_dump.txt.gz)

**Comment by ivan4th** [comment]
This is indeed very strange... The dump shows both kube-dns and kubernetes-dashboard to be running correctly. Could you please execute the following commands immediately after trying to start the cluster:
```
kubectl get pod -l k8s-app=kube-dns -n kube-system
kubectl get pod -l k8s-app=kube-dns -n kube-system -o jsonpath='{ .items[*].status.conditions[?(@.type == "Ready")].status }'
kubectl get pod -l app=kubernetes-dashboard -n kube-system
kubectl get pod -l app=kubernetes-dashboard -n kube-system -o jsonpath='{ .items[*].status.conditions[?(@.type == "Ready")].status }'
kubectl get pods --all-namespaces -o wide
```

and paste the output?

**Comment by mail2fish** [comment]
kubectl get pod -l k8s-app=kube-dns -n kube-system
NAME                        READY     STATUS    RESTARTS   AGE
kube-dns-855bdc94cb-5kn98   3/3       Running   0          8m

--------------------------

kubectl get pod -l k8s-app=kube-dns -n kube-system -o jsonpath='{ .items[*].status.conditions[?(@.type == "Ready")].status }'
True

--------------------------

kubectl get pod -l app=kubernetes-dashboard -n kube-system
NAME                                    READY     STATUS             RESTARTS   AGE
kubernetes-dashboard-6b5bdcfbc6-w2ckn   0/1       ImagePullBackOff   0          9m

--------------------------

kubectl get pod -l app=kubernetes-dashboard -n kube-system -o jsonpath='{ .items[*].status.conditions[?(@.type == "Ready")].status }'
False

--------------------------

kubectl get pods --all-namespaces -o wide
NAMESPACE     NAME                                    READY     STATUS             RESTARTS   AGE       IP           NODE
kube-system   etcd-kube-master                        1/1       Running            2          6d        10.192.0.2   kube-master
kube-system   kube-apiserver-kube-master              1/1       Running            2          6d        10.192.0.2   kube-master
kube-system   kube-controller-manager-kube-master     1/1       Running            2          9m        10.192.0.2   kube-master
kube-system   kube-dns-855bdc94cb-5kn98               3/3       Running            0          10m       10.244.3.3   kube-node-2
kube-system   kube-proxy-4brg8                        1/1       Running            0          10m       10.192.0.4   kube-node-2
kube-system   kube-proxy-8pgqm                        1/1       Running            0          10m       10.192.0.3   kube-node-1
kube-system   kube-proxy-cvrzp                        1/1       Running            0          10m       10.192.0.2   kube-master
kube-system   kube-scheduler-kube-master              1/1       Running            2          6d        10.192.0.2   kube-master
kube-system   kubernetes-dashboard-6b5bdcfbc6-w2ckn   0/1       ImagePullBackOff   0          10m       10.244.2.5   kube-node-1

**Comment by ivan4th** [comment]
Could you please do `kubectl describe pod` on the `kubernetes-dashboard` pod:
```
kubectl describe pod -n kube-system -l app=kubernetes-dashboard
```
There's likely a problem communicating with `gcr.io` docker registry, although I wonder why other images were pulled successfully

**Comment by mail2fish** [comment]
Name:         kubernetes-dashboard-6b5bdcfbc6-zsskj
Namespace:    kube-system
Node:         kube-node-1/10.192.0.3
Start Time:   Mon, 11 Jun 2018 09:20:28 +0800
Labels:       app=kubernetes-dashboard
              pod-template-hash=2616879672
Annotations:  kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"kube-system","name":"kubernetes-dashboard-6b5bdcfbc6","uid":"417f4054-6549-11e8-b...
              scheduler.alpha.kubernetes.io/tolerations=[
  {
    "key": "dedicated",
    "operator": "Equal",
    "value": "master",
    "effect": "NoSchedule"
  }
]

Status:         Pending
IP:             10.244.2.8
Controlled By:  ReplicaSet/kubernetes-dashboard-6b5bdcfbc6
Containers:
  kubernetes-dashboard:
    Container ID:   
    Image:          gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.0
    Image ID:       
    Port:           9090/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Liveness:       http-get http://:9090/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-stf79 (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  default-token-stf79:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-stf79
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.alpha.kubernetes.io/notReady:NoExecute for 300s
                 node.alpha.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age                From                  Message
  ----     ------                 ----               ----                  -------
  Normal   Scheduled              11m                default-scheduler     Successfully assigned kubernetes-dashboard-6b5bdcfbc6-zsskj to kube-node-1
  Normal   SuccessfulMountVolume  11m                kubelet, kube-node-1  MountVolume.SetUp succeeded for volume "default-token-stf79"
  Normal   SandboxChanged         10m (x5 over 10m)  kubelet, kube-node-1  Pod sandbox changed, it will be killed and re-created.
  Warning  Failed                 9m (x2 over 10m)   kubelet, kube-node-1  Failed to pull image "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.0": rpc error: code = Unknown desc = Error response from daemon: Get https://gcr.io/v1/_ping: dial tcp 108.177.125.82:443: i/o timeout
  Normal   Pulling                9m (x3 over 11m)   kubelet, kube-node-1  pulling image "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.0"
  Normal   BackOff                6m (x12 over 10m)  kubelet, kube-node-1  Back-off pulling image "gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.0"
  Warning  FailedSync             1m (x32 over 10m)  kubelet, kube-node-1  Error syncing pod

**Comment by ivan4th** [comment]
That's the culprit:
```Get https://gcr.io/v1/_ping: dial tcp 108.177.125.82:443: i/o timeout```

Does `docker pull gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.0` work on your system? If you have a proxy server that might help, try setting `DIND_HTTPS_PROXY=http://...` (specify that server)

**Comment by mail2fish** [comment]
Yes! After I pulled kubernetes-dashboard-amd64:v1.6.0  manually and up the cluster again, the cluster start successfully.

Thanks @ivan4th. That's so cool.

**Comment by ivan4th** [comment]
You're welcome. It looks like you have intermittent connectivity issues with some of Google IPs, though. So if the problem repeats, pls try proxy / VPN, I suspect it may have to deal with some of Google IPs being blocked in China. Closing the issue for now.
