### ISSUE TITLE
Unable to access EXTERNAL_IP of K8s service from k8s node

### ISSUE THREAD

**Issue by aramisjohnson** [kubernetes-sigs/kubeadm-dind-cluster#13]
Hello,

Yes its that time again. So I ran into an issue where I use your v1.5 script to set up a 2 node k8s cluster. I then create a service which uses an external ip like 

NAME           CLUSTER-IP       EXTERNAL-IP    PORT(S)          AGE
web            10.106.52.236    172.17.4.201   80:32023/TCP     1h

i can hit the service from the master k8s node like so;
curl 10.106.52.236:80 --> success 200
curl 0.0.0.0:32023 --> success 200
curl 127.0.0.1:32023 --> success 200

However whether I am on the master of the docker host, I cannot hit that EXTERNAL-IP of 172.17.4.201, is there any reason you can think of why this would be an issue?

Thanks,
aramisjohnson

**Comment by daggerok** [comment]
it would be nice to have such possibility to access exposed services

**Comment by riuvshin** [comment]
does this mean that with this dind cluster you can't deploy app, create service with ingress and reach that application from the host (not from the cluster) ?

**Comment by lukaszo** [comment]
How exactly did you assign this external IP? 

@riuvshin you can use service with type=NodePort to access app
