### ISSUE TITLE
Unable to enable PersistentLocalVolumes

### ISSUE THREAD

**Issue by wallrj** [kubernetes-sigs/kubeadm-dind-cluster#139]
I want to use PersistentLocalVolumes in a kubeadm-dind-cluster, but there doesn't seem to be a way to add the necessary `--feature-gates=PersistentLocalVolumes=true` argument to the API server, scheduler and controller manager.

Additionally, when I hack the main script to use a custom `kubeadm.conf.tmpl` file, I then run into a problem where the `wrapkubeadm` script drops and replaces the `--feature-gates` argument from kubeadm.conf. See:
 * https://github.com/kubernetes-sigs/kubeadm-dind-cluster/commit/2d1f8e6dd97d7aad51814f6092357534135b40cd#diff-94a5a32bdd335b47ad3760d4da9ea020R50

**Comment by ivan4th** [comment]
For now kubelet config is a bit hacky, will it suit you if I just always enable this feature gate when k8s version supports it?

**Comment by wallrj** [comment]
That'd be good.
Or else `--feature-gates=AllAlpha=true` which should enable all available features on all versions.
That might also help resolve #118, #122

**Comment by ivan4th** [comment]
I've managed to test local PVs / PVCs successfully with `dind-cluster-v1.10.sh` (local PVs are beta in k8s 1.10, so no need for feature gates).

I've used the following YAML:
```yaml
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-local-pv
  labels:
    testpv: local
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /local-pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kube-node-1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: example-local-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 500Gi
  selector:
    matchLabels:
      testpv: local
---
kind: Pod
apiVersion: v1
metadata:
  name: test-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - /bin/sh
    - -c
    - sleep 30000
    volumeMounts:
    - mountPath: "/testpvc"
      name: testpvc
  volumes:
  - name: testpvc
    persistentVolumeClaim:
      claimName: example-local-claim
```

Tested it like this:
```bash
$ docker exec kube-node-1 mkdir /local-pv
$ kubectl apply -f ~/rmme/local-pvc.yaml
storageclass.storage.k8s.io/local-storage created
persistentvolume/example-local-pv created
persistentvolumeclaim/example-local-claim created
pod/test-pod created
$ kubectl get pods -w
NAMESPACE     NAME                                    READY     STATUS    RESTARTS   AGE       IP           NODE
default   test-pod   0/1       Pending   0         0s        <none>    <none>
default   test-pod   0/1       Pending   0         0s        <none>    <none>
default   test-pod   0/1       Pending   0         1s        <none>    kube-node-1
default   test-pod   0/1       ContainerCreating   0         1s        <none>    kube-node-1
default   test-pod   1/1       Running   0         6s        10.244.2.4   kube-node-1
^C
$ kubectl exec -it test-pod touch /testpvc/foobar
$ docker exec kube-node-1 ls /local-pv
foobar
```
Frankly I'm not quite sure we should add local PV support for k8s 1.9 and earlier, or do you really need it?

**Comment by wallrj** [comment]
We're still testing https://github.com/jetstack/navigator against Kubernetes 1.7 and we'd like to use dind-cluster rather than minikube, so we do need it.

It'd be great if there was a general mechanism to enable feature gates for each of the k8s components, not just for local PVs.

**Comment by everpeace** [comment]
I think https://github.com/kubernetes-sigs/kubeadm-dind-cluster/pull/149 fixed this issue. you can customize `feature-gates`. 

@wallrj  could you try `master` branch again??

if the pr is what you expected,   could you close this issue? 🙇

**Comment by imriss** [comment]
This example uses `kubeadm-dind-cluster` with local persistent volume on the host: [p1-local-persistent-volume-host](https://github.com/imriss/kubernetes_factory/tree/master/p1-local-persistent-volume-host)

**Comment by LiamHe** [comment]
In addition to what @ivan4th has provided, we can mount our local directory (like datasets) to kube-node-1 first. To do so, change the last statement of function `dind::run` in `dind-cluster-*.sh` to   
```bash
docker run \
	 -e IP_MODE="${IP_MODE}" \
         -e KUBEADM_SOURCE="${KUBEADM_SOURCE}" \
         -e HYPERKUBE_SOURCE="${HYPERKUBE_SOURCE}" \
         -d --privileged \
         --net "$(dind::net-name)" \
         --name "${container_name}" \
         --hostname "${container_name}" \
         -l "${DIND_LABEL}" \
         -v "${volume_name}:/dind" \
         --mount type=bind,source=/path/to/local/,target=/local-pv \
         ${opts[@]+"${opts[@]}"} \
         "${DIND_IMAGE}" \
         ${args[@]+"${args[@]}"}
```
Then run `dind-cluster-v1.11.sh down && dind-cluster-v1.11.sh clean && dind-cluster-v1.11.sh up` to mount your local filesystem.
