### ISSUE TITLE
"./dind-cluster-v1.8.sh up" failed on windows 10

### ISSUE THREAD

**Issue by wudongyin** [kubernetes-sigs/kubeadm-dind-cluster#157]
$ ./dind-cluster-v1.8.sh up
* Making sure DIND image is up to date
v1.8: Pulling from mirantis/kubeadm-dind-cluster
Digest: sha256:cc354cea2ed80ff57aa61ee5f78baf9a28192f7ed52b83fcce9eb956aac3d07b
Status: Image is up to date for mirantis/kubeadm-dind-cluster:v1.8
/c/Users/xxx/.kubeadm-dind-cluster/kubectl-v1.8.11: OK
* Starting DIND container: kube-master
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Mount denied:
The source path "C:/Program Files/Git/boot;C"
doesn't exist and is not known to Docker.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
Error: No such container: kube-master

**Comment by ivan4th** [comment]
Unfortunately I don't have access to a Windows machine right now, but could you please
change this line https://github.com/kubernetes-sigs/kubeadm-dind-cluster/blob/master/fixed/dind-cluster-v1.10.sh#L38
to `using_linuxkit=1` and see if it helps? Thanks!

**Comment by wudongyin** [comment]
@ivan4th Thank you for your help. 
I downloaded the V1.10.sh, modified line 38, and run the file.
Here is the result:
$ ./dind-cluster-v1.10.sh up
* Making sure DIND image is up to date
v1.10: Pulling from mirantis/kubeadm-dind-cluster
d2519f41f710: Already exists
8bedb40dd1fe: Already exists
e6792642eea7: Already exists
949bd49c5dfa: Already exists
1393d505ac52: Already exists
6c4966f8ef53: Already exists
5b5c373abe4c: Already exists
711efcb00f86: Already exists
15aae4c3e8a0: Already exists
4351dba3b488: Already exists
5cac2230e808: Already exists
b6c77402b97b: Already exists
51844e077e71: Already exists
db28a48cb46c: Already exists
e512774399d2: Already exists
7047b38e312e: Already exists
c0713876e67f: Already exists
17b990c310d0: Already exists
986052c22098: Pulling fs layer
1ae26d8c3dbe: Pulling fs layer
1ae26d8c3dbe: Verifying Checksum
1ae26d8c3dbe: Download complete
986052c22098: Verifying Checksum
986052c22098: Download complete
986052c22098: Pull complete
1ae26d8c3dbe: Pull complete
Digest: sha256:ced12ce28389333f2dee9fd2429f0f1c7de82bc4b4cfc7013379e4e469396c6a
Status: Downloaded newer image for mirantis/kubeadm-dind-cluster:v1.10
* Saving a copy of docker host's /lib/modules
Unable to find image 'busybox:1.26.2' locally
1.26.2: Pulling from library/busybox
27144aa8f1b9: Pulling fs layer
27144aa8f1b9: Download complete
27144aa8f1b9: Pull complete
Digest: sha256:be3c11fdba7cfe299214e46edc642e09514dbb9bbefcd0d3836c05a1e0cd0642
Status: Downloaded newer image for busybox:1.26.2
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"C:/Program Files/Git/usr/bin/sh\": stat C:/Program Files/Git/usr/bin/sh: no such file or directory": unknown.
