### ISSUE TITLE
Error from image kubeadm-dind-cluster:v1.10 bind mount failed: `/boot` does not exists

### ISSUE THREAD

**Issue by antoine-morisseau** [kubernetes-sigs/kubeadm-dind-cluster#160]
Hello, i have an issue where docker can't start the container due to a missing folder.
I use a Synology NAS with docker on it (`docker version 17.05.0-ce`)
the issue is it's a customized unix system based on BSD. It does not have a /boot folder.

I wanted to understand why and where this boot folder i used.

**Comment by cscetbon** [comment]
I'm surprised you didn't get an answer since July. I'm looking for the same answer and I don't understand why it needs it. I don't wanna have to create a `/boot` just for dind to work ...

**Comment by cscetbon** [comment]
@antoine-morisseau if you're still stuck have a look at https://github.com/kubernetes-sigs/kubeadm-dind-cluster/pull/246. That's how I fixed the issue on my Mac. You'd probably do the same
