### ISSUE TITLE
stable release tags

### ISSUE THREAD

**Issue by gregwebs** [kubernetes-sigs/kubeadm-dind-cluster#195]
This is a great project, and I am glad there is a lot of development on it to push it forward. But it seems that there is a fair amount of instability on master right now.
It would be very helpful to have some release tags to use for installing.
I am creating a tutorial that requires a multi-node Kubernetes install. Running kubeadm-dind-cluster is recommended, but now I don't know what commit I should be recommending.

**Comment by jellonek** [comment]
I agree on that this should be done soon.
For this moment I would suggest to use https://github.com/kubernetes-sigs/kubeadm-dind-cluster/commit/64a2befa65ce23475158b65793e56d4bc1ae0a79 as a latest stable commit.

**Comment by gregwebs** [comment]
Thanks! I have local volume mounting issues on that commit that I don't see on [our fork](https://github.com/pingcap/kubeadm-dind-cluster). I haven't tracked down where the issue diverges yet.

```
Error: failed to start container "tidb-operator": Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/etc/localtime\\\" to rootfs \\\"/dind/docker/overlay2/acd1036e479c09a05eb76450dc0ba58ade6e5c2f0d1eff48b4729880d648e421/merged\\\" at \\\"/dind/docker/overlay2/acd1036e479c09a05eb76450dc0ba58ade6e5c2f0d1eff48b4729880d648e421/merged/etc/localtime\\\" caused \\\"not a directory\\\"\""
```

**Comment by pigmej** [comment]
What about https://github.com/kubernetes-sigs/kubeadm-dind-cluster/blob/master/fixed/dind-cluster-stable.sh ? That's the current "sub-optimal" way. (per discussion: https://github.com/kubernetes-sigs/kubeadm-dind-cluster/issues/115)

@ivan4th is currently working on containerizing "core" scripts, and leaving just "frontend" to end user, that should fix your problem definitely.

**Comment by gregwebs** [comment]
Great!
