### ISSUE TITLE
Add knob to allow user to select kube-proxy in IPVS mode

### ISSUE THREAD

**Issue by pmichali** [kubernetes-sigs/kubeadm-dind-cluster#208]
To run in this mode, kubeadm.conf needs to have the lines:
```
kubeProxy:
    config:
        mode: "ipvs"
```

Currently, the only way to do this, is to modify the kubeadm.conf.tmpl file and then build the DinD image locally. It would be useful to be able to select this via a knob.

Related questions are:
- Should we provide a knob to allow masqueradeAll to be set to false, or is this required to be true for k-d-c (and if so, why)?
- Should we provide an option for the user to be able to specify the value for clusterCIDR used by kube-proxy? For IPv4 it is set to the docker0 network, for IPv6 it is set to "".

As I understand it, IPVS will use ipset, when masqueradeAll is true and/or clusterCIDR != "".

Ref: https://kubernetes.io/blog/2018/07/09/ipvs-based-in-cluster-load-balancing-deep-dive/

**Comment by lukaszo** [comment]
I hope that bot will not close it again
