### ISSUE TITLE
Using 0.0.0.0 to bind port on container for AWS.

### ISSUE THREAD

**Issue by Gavin89** [kubernetes-sigs/kubeadm-dind-cluster#213]
Hey, I was looking to use this for my AWS ec2 instance, and I noticed the kube-master got bound to 127.0.0.1, which means my kubectl on my machine is unable to access the port. Could you maybe have an option to say if cloud, then use 0.0.0.0? I updated mine manually to reflect this, and I was then able to connect to my cluster in docker via kubectl

**Comment by ivan4th** [comment]
kube-master uses an insecure port right now. This is something to be fixed, too, but to provide some minimum security it's advised to forward apiserver port over ssh instead. Also, you can forward the port using docker, see [this script](https://github.com/kubernetes-sigs/kubeadm-dind-cluster/blob/master/build/portforward.sh) used by kubeadm-dind-cluster CircleCI jobs for example.
