### ISSUE TITLE
Hang in Running kubeadm

### ISSUE THREAD

**Issue by livingmine** [kubernetes-sigs/kubeadm-dind-cluster#217]
### Steps to reproduce:
Run ```./dind-cluster-v1.8.sh up``` command

### Environments:
1. Ubuntu 18.04
2. kubeadm version: &version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:59:42Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
3. kubectl version: Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
4. kubelet version: Kubernetes v1.11.3

### Expected outcome:
Cluster successfully created.

### Actual outcome:
Hang in ```[init] This often takes around a minute; or longer if the control plane images have to be pulled.```

### Extra informations:
Output of ```sudo journalctl -u kubelet | tail -f```:
```9251 server.go:245] unable to load client CA file /var/lib/localkube/certs/ca.crt: open /var/lib/localkube/certs/ca.crt: no such file or directory```

Is this caused by missing client CA? If so, i'm not sure why is it looking for this non-existent path ``` /var/lib/localkube/certs/ca.crt```.

**Comment by jotamorais** [comment]
I'm experiencing the same isue.
