### ISSUE TITLE
Need help with exposing the master's secure port

### ISSUE THREAD

**Issue by isyarov** [kubernetes-sigs/kubeadm-dind-cluster#221]
Hi guys, 
I really appreciate the work you've done, it's awesome.

I want to use this for testing purposes and i need to call the master api server from a different machine. Is there a way to expose the secure and insecure ports without modifying the script? Currently the master's insecure port gets exposed, but is bound to 127.0.0.1 and thus i cannot reach it from another machine, only from the host machine and from the container itself. Maybe I am missing something obvious, I apologize if that's the case.

Thanks in advance,
Regards,
Ivan

**Comment by IljaKroonen** [comment]
@isyarov Did you succeed?

**Comment by isyarov** [comment]
@IljaKroonen no, I did not. I succeeded it only by modifying the script.
