### ISSUE TITLE
Cannot build kubetest for e2e behind http proxy

### ISSUE THREAD

**Issue by vlad-belogrudov** [kubernetes-sigs/kubeadm-dind-cluster#224]
I set DIND_*PROXY variables and can run cluster successfully with 1.10 script. Unfortunately proxies are not taken into account when building e2e:

https://github.com/kubernetes-sigs/kubeadm-dind-cluster/blob/master/fixed/dind-cluster-v1.10.sh#L1758

It would be nice to have here those proxies as well or to build kubetest elsewhere and then run e2e (e.g. to avoid networking issues due to proxies set).

As temp solution:

1757          cluster/kubectl.sh config use-context dind &&
1758          HTTPS_PROXY=${DIND_HTTP_PROXY} go get -u k8s.io/test-infra/kubetest &&
1759          go run hack/e2e.go -- --v 6 --test --check-version-skew=false --test_args='${test_args}'"

**Comment by mestery** [comment]
I see something similar here:

```
Removing intermediate container 505606a76d5f
Successfully built 7fe37431ce8f
Created symlink /etc/systemd/system/multi-user.target.wants/kubelet.service → /lib/systemd/system/kubelet.service.
[init] using Kubernetes version: v1.11.0
[preflight] running pre-flight checks
I1008 19:12:05.461158    1023 feature_gate.go:230] feature gates: &{map[]}
        [WARNING HTTPProxy]: Connection to "https://10.192.0.2" uses proxy "http://proxy-wsa.esl.cisco.com:80". If that is not intended, adjust your proxy settings
        [WARNING HTTPProxyCIDR]: connection to "10.96.0.0/12" uses proxy "http://proxy-wsa.esl.cisco.com:80". This may lead to malfunctional cluster setup. Make sure that Pod and Services IP ranges specified correctly as exceptions in proxy configuration
        [WARNING FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables does not exist
        [WARNING Swap]: running with swap on is not supported. Please disable swap
        [WARNING FileExisting-crictl]: crictl not found in system path
```

**Comment by murdav** [comment]
I have the same issue. Did you solve it?

**Comment by Starfight** [comment]
Environment variable NO_PROXY seems not to be propagate in docker containers, I have temporary patch it with setting `-e NO_PROXY=${DIND_NO_PROXY}` in docker run options for master and node.

**Comment by mrbobbytables** [comment]
Closing as this project is being deprecated and retired in favor of [KinD](https://github.com/kubernetes-sigs/kind).

Please see this issue for more details:
https://github.com/kubernetes/org/issues/1016

/close
