### ISSUE TITLE
met error when do git clone

### ISSUE THREAD

**Issue by jerryjedi** [kubernetes-sigs/kubeadm-dind-cluster#227]
I follow the instruction to git clone the code to local:
git clone git@github.com:kubernetes-sigs/kubeadm-dind-cluster.git ~/dind
but cmd report " Permission denied (publickey).， fatal: Could not read from remote repository.“. 
I have already config the SSH key of github and tested "ssh -T git@github.com" successfully. 
Finally I used "git clone https://github.com/kubernetes-sigs/kubeadm-dind-cluster.git ~/dind" to clone the code to local. 
So does instruction need to change for this?

**Comment by jellonek** [comment]
I think that you are right. My linked above PR fixes that.
