### ISSUE TITLE
Persist kubernetes objects

### ISSUE THREAD

**Issue by allamand** [kubernetes-sigs/kubeadm-dind-cluster#232]
Hello,

I would like to know if it is possible to persist kubernetes state and objects bretween a down and a up or reup ?

I would like to uses dind cluster to deploy some apps, then I would like to shut it down and brings it up later. I see that it uses docker volumes, so that I can persist data from my pods in local-volumes in the docker volume, but it seams that all kubernetes objects are gone after a reboot.

Is there a way to make them persists ?

Thanks

**Comment by allamand** [comment]
For the moment I'm doing manual `docker pause kube-master kube-node-1` and later `docker unpause kube-master kube-node1` but maybe there is integrated tool for doing better

**Comment by cscetbon** [comment]
What's the best way to see it implemented ? provide a PR ? Do we agree on the usefulness of that feature ?
