### ISSUE TITLE
installation doesn't go through

### ISSUE THREAD

**Issue by ozbillwang** [kubernetes-sigs/kubeadm-dind-cluster#243]
I got this when run `./dind-cluster-v1.8.sh up`

```
[init] This often takes around a minute; or longer if the control plane images have to be pulled.
^@^@^@^@^@^@^@^@^@
```
I guess it is because the company outbound rules.

I need temporary open the whitelists for any outbound dns name, for example, I need open `*.github.com` to allow the access to github.

I have added below, anything else I need add to whitelists to install this `kubeadm-dind-cluster`

```
.googleapis.com
.rawgit.com
.github.com
.docker.io
.docker.com
```

**Comment by lukaszo** [comment]
It's message from kubeadm. It downloads images from `k8s.gcr.io` domain

**Comment by ozbillwang** [comment]
Thanks, but still hold for long time, maybe there are some other issues.

**Comment by jellonek** [comment]
The fastest way to debug that would be to use wireshark to monitor what outgoing communication tries to be established. That doesn't even require looking into sources/settings.

**Comment by ozbillwang** [comment]
Thanks, @ivan4th 

I saw some errors with the dump:

The error is

>The connection to the server localhost:8080 was refused - did you specify the right host or port?

The container is running

>30b231f01b62        mirantis/kubeadm-dind-cluster:v1.10                                      "/sbin/dind_init s..."   7 minutes ago       Up 7 minutes              127.0.0.1:32768->8080/tcp   kube-master

I will check why I can't connect to localhost with port 8080
```
ec2-user@ip-10-61-71-85:~/k8s$ curl localhost:8080
curl: (7) Failed to connect to ::1: No route to host
```
