### ISSUE TITLE
New kubeadm.conf templates are not in the stable image

### ISSUE THREAD

**Issue by combor** [kubernetes-sigs/kubeadm-dind-cluster#245]
After https://github.com/kubernetes-sigs/kubeadm-dind-cluster/pull/237 was merged the `stable` container was not updated so it doesn't contain new templates. This results in startup failures:

```
sed: can't read /etc/kubeadm.conf.1.10.tmpl: No such file or directory
```

**Comment by combor** [comment]
Just checked - it works OK from the stable branch. Should this be documented somewhere that `dind-cluster-stable.sh` is stable only on `stable` branch?

**Comment by lukaszo** [comment]
Yeah, good idea. I will create a PR

**Comment by combor** [comment]
Thanks! I'll close this issue.
