### ISSUE TITLE
Registry proxy cache container

### ISSUE THREAD

**Issue by cscetbon** [kubernetes-sigs/kubeadm-dind-cluster#248]
One issue with Docker in Docker is that each kube node that uses a dind container pulls the images it needs. So having 3 nodes, the same image could be downloaded at most 3 times. There should be the possibility of having a local registry proxy cache to avoid having to download an image more than once. 
Something like https://blog.docker.com/2015/10/registry-proxy-cache-docker-open-source.

**Comment by ivan4th** [comment]
This feature is already implemented, see #93 
Just need to add docs for it ...
