### ISSUE TITLE
How to enable kubectl autocompletion with this cluster

### ISSUE THREAD

**Issue by abdennour** [kubernetes-sigs/kubeadm-dind-cluster#264]
I would expect to have a kubeconfig to point the kubectl calls to the cluster. However, the approach is to use a custom "kubectl"  which is `$HOME/.kubeadm-dind-cluster/kubectl`.

Can we enable bash/zsh autocompletion with this binary ?

**Comment by jellonek** [comment]
Just add `~/.kubeadm-dind-cluster` to your `$PATH`.
