### ISSUE TITLE
ERROR: "Job for docker.service canceled." error when DIND*_PROXY set

### ISSUE THREAD

**Issue by hawsers** [kubernetes-sigs/kubeadm-dind-cluster#280]
https://github.com/kubernetes-sigs/kubeadm-dind-cluster/blob/3fc17d5c4702b9dccf791837a220d8606659ffde/fixed/dind-cluster-v1.13.sh#L2247
 
Test in CentOS 7.5, after comment this line, proxy work well.

**Comment by murdav** [comment]
@hawsers thanks so much!
I use an Ubuntu 18 virtual machine (VirtualBox) on a Window host.
Initially it didn't work I had some proxy errors hence I added in the .bashrc:

DIND_HTTP_PROXY=
DIND_HTTPS_PROXY=
DIND_NO_PROXY=

But I had your same error that was solved commenting that line,
I'm curious how were you able to spot it?
Huge thanks!

**Comment by pigmej** [comment]
Seems the same as #288

**Comment by morningspace** [comment]
I think this has been fixed w/ the new released pre-configured scripts, e.g. https://github.com/kubernetes-sigs/kubeadm-dind-cluster/releases/download/v0.2.0/dind-cluster-v1.14.sh
