### ISSUE TITLE
docker on zfs needs additional package

### ISSUE THREAD

**Issue by pgeorgi** [kubernetes-sigs/kubeadm-dind-cluster#290]
When using Docker with the zfs backend, the docker binary calls into the zfs binary to gather information about volumes. In a DinD setup, the in-docker binary needs to have the binary available within the container (and that works), so please consider adding zfsutils-linux to the container.

**Comment by mrbobbytables** [comment]
Closing as this project is being deprecated and retired in favor of [KinD](https://github.com/kubernetes-sigs/kind).

Please see this issue for more details:
https://github.com/kubernetes/org/issues/1016

/close
