### ISSUE TITLE
dind::run duplicates command options

### ISSUE THREAD

**Issue by zenlambda** [kubernetes-sigs/kubeadm-dind-cluster#291]
I wanted to map a few extra ports on the master so I tried the following (so maybe i could setup an ingress):

    MASTER_EXTRA_OPTS="` -p 8887:8887 " NUM_NODES=3 ./dind-cluster-v1.13.sh up

However this results in the following error:

   Bind for 0.0.0.0:8887 failed: port is already allocated.

This is because the extra opts are [copied in _twice_](https://github.com/kubernetes-sigs/kubeadm-dind-cluster/blob/master/dind-cluster.sh#L957). If this line is removed or [line 949](https://github.com/kubernetes-sigs/kubeadm-dind-cluster/blob/master/dind-cluster.sh#L949) is changed to only initialise an empty array then the error does not occur, and ports can be mapped.

**Comment by mrbobbytables** [comment]
Closing as this project is being deprecated and retired in favor of [KinD](https://github.com/kubernetes-sigs/kind).

Please see this issue for more details:
https://github.com/kubernetes/org/issues/1016

/close
