### ISSUE TITLE
v1.14 script?

### ISSUE THREAD

**Issue by wk8** [kubernetes-sigs/kubeadm-dind-cluster#302]
Now that kube 1.14 is out, would be great to be able to use this great project to stand up 1.14 clusters too :) !

(would happily do it, but I don't have the rights neither to Docker hub nor to Github to do that).

Thanks again!

**Comment by morningspace** [comment]
It has been done... You should be able to download the 1.14 script from https://github.com/kubernetes-sigs/kubeadm-dind-cluster/releases/download/v0.2.0/dind-cluster-v1.14.sh.
