### ISSUE TITLE
v1.12 kubeadm template is not setting cluster dns

### ISSUE THREAD

**Issue by jlyheden** [kubernetes-sigs/kubeadm-dind-cluster#304]
This causes the dind cluster with a custom service cidr to have broken dns, ie the default cluster-dns from kubelet (10.96.0.10) will be injected in resolv.conf in the pods.

**Comment by mrbobbytables** [comment]
Closing as this project is being deprecated and retired in favor of [KinD](https://github.com/kubernetes-sigs/kind).

Please see this issue for more details:
https://github.com/kubernetes/org/issues/1016

/close
