### ISSUE TITLE
DNS issues resolving svc.cluster.local addresses

### ISSUE THREAD

**Issue by fadams** [kubernetes-sigs/kubeadm-dind-cluster#305]
Hello, I've been using dind-cluster-v1.13.sh from releases to evaluate OpenFaaS https://github.com/openfaas and Oracle Fn https://github.com/fnproject/fn and I appear to have hit similar issues with both.

With OpenFaaS I first followed their instructions https://docs.openfaas.com/deployment/kubernetes/ that used kubectl with yaml and that worked fine for me. I later got a bit more adventurous and followed their instructions to deploy using helm and in that case it didn't work.

I rendered the chart to a kubernetes manifest like this:
```
helm template faas-netes/chart/openfaas \
    --name openfaas \
    --namespace openfaas  \
    --set functionNamespace=openfaas-fn > openfaas.yaml
```
To try and work out what the differences might be and I eventually noticed that in the basic yaml deployment I had addresses that looked like this:
```
        - name: direct_functions_suffix
          value: "openfaas-fn.svc.cluster.local."
        - name: faas_nats_address
          value: "nats.openfaas.svc.cluster.local."
```
That is to say the relevant addresses had a trailing period. In the openfaas.yam rendered from the helm chart I noticed that the equivalent addresses did not have the trailing period.
```
        - name: direct_functions_suffix
          value: "openfaas-fn.svc.cluster.local"
        - name: faas_nats_address
          value: "nats.openfaas.svc.cluster.local"
```
When I edited that file to add the trailing period the application then deployed fine and worked.

I had a similar experience with Fn where I had an address
```
          - name: FN_RUNNER_ADDRESSES
            value: fn-fn-runner.fn.svc.cluster.local:9191
```
which was failing to be resolved and again when I edited to add the trailing period after the .local things started working.

I queried this in both projects, but the responses have been along the lines of "works for me, try a different Kubernetes deployment", which is a bit unhelpful.

I'm pretty inexperienced with Kubernetes and I'm not exactly a DNS expert either but as far as I am aware a trailing period signifies an absolute/fully-qualified address so without the trailing period the lookup will try to resolve the name.

I've docker execed onto kube-node-1 to look at resolv.conf and this is what I see
```
cat /etc/resolv.conf
search localdomain
nameserver 10.192.0.3
options ndots:0

#fixed#
```
But TBH I'm not sure what I should be expecting to see on a Kubernetes Node. The kube-master looks the same apart from having its own IP address referenced in the nameserver line.

From man resolv.conf it looks like the default for ndots is 1 "meaning that if there are any dots in a name, the name will be tried first as an absolute name  before  any search  list  elements are appended to it".

I also came across https://github.com/moby/moby/issues/32093

Hmm I wonder. My setup is using kubeadm-dind-cluster on my PC running Linux Mint which has Avahi set up so machines on my local network can be resolved via a ".local" so I wonder if ndots:0 is causing it to try and resolve via Avahi - I did say I'm no DNS expert :-D

Is there any config on kubeadm-dind-cluster that might enable me to try different ndots settings?

MTIA for any insight that you might be able to shed on this, cheers!

**Comment by mrbobbytables** [comment]
Closing as this project is being deprecated and retired in favor of [KinD](https://github.com/kubernetes-sigs/kind).

Please see this issue for more details:
https://github.com/kubernetes/org/issues/1016

/close
