### ISSUE TITLE
rbac rules not enforced

### ISSUE THREAD

**Issue by nicks** [kubernetes-sigs/kubeadm-dind-cluster#309]
Repro steps:
1) Run

```
$ ./fixed/dind-cluster-v1.13.sh up
```

2) Create a service account that's restricted to a specific namespace. If you need help, here's an example script:

https://github.com/windmilleng/k8s-rbac-testing

3) With the service account, run

```
$ kubectl get pods --all-namespaces
```

Expected result:
Should get a permission denied error. Verified this works as expected with other clusters I tried (KIND, Minikube)

Actual result:
No permissions enforced

What am I doing wrong?

**Comment by mrbobbytables** [comment]
Closing as this project is being deprecated and retired in favor of [KinD](https://github.com/kubernetes-sigs/kind).

Please see this issue for more details:
https://github.com/kubernetes/org/issues/1016

/close
