### ISSUE TITLE
Move DIND --> retired in favor of KIND

### ISSUE THREAD

**Issue by timothysc** [kubernetes-sigs/kubeadm-dind-cluster#310]
@ivan4th - in sig-cluster-lifecycle we wanted to have a discussion with owners of DIND to see if can move it to retired in favor of KIND given that there is >= feature parity there. 

/cc @BenTheElder 
/assign @ivan4th

**Comment by ivan4th** [comment]
Can we move kubeadm-dind-cluster back under github.com/Mirantis (so that there'll be redirects for it)? I'll also add a notice to README about kind being preferred

**Comment by mrbobbytables** [comment]
Little bit redundant but -
Closing as this project is being deprecated and retired in favor of [KinD](https://github.com/kubernetes-sigs/kind).

Please see this issue for more details:
https://github.com/kubernetes/org/issues/1016

/close
