### ISSUE TITLE
dind::at-least-kubeadm-1-8 function fails

### ISSUE THREAD

**Issue by danehans** [kubernetes-sigs/kubeadm-dind-cluster#47]
I am using master for kdc and k8s and the dind::at-least-kubeadm-1-8 function does not work properly for me. My deployment completes successfully, but kubeadm init does not reference kubeadm.conf. When I remove the reference to dind::at-least-kubeadm-1-8 in the dind::init function, kubeadm init works properly by using kubeadm.conf. Here are a few details from my deployment.

I have to use `sudo -E` when calling the gce-setup.sh script, otherwise I get permission errors when running kdc:
```
$ . /Users/daneyonhansen/code/go/src/github.com/Mirantis/kubeadm-dind-cluster/gce-setup.sh
<SNIP>
chown: /Users/daneyonhansen/code/go/src/k8s.io/kubernetes/_output/images/kube-build:build-f0510dd6c7-5-v1.9.1-1/Dockerfile: Operation not permitted
<SNIP>
```

When I run with `sudo -E`, my deployment completes, but does not use kubeadm.conf:
```
$ sudo -E /Users/daneyonhansen/code/go/src/github.com/Mirantis/kubeadm-dind-cluster/gce-setup.sh
<SNIP>
* Starting DIND container: kube-master
* Running kubeadm: init --pod-network-cidr=10.244.0.0/16 --skip-preflight-checks
<SNIP>
```

It appears the regex used in dind::at-least-kubeadm-1-8 does not work:
```
$ docker exec kube-master kubeadm version -o short 2>/dev/null|sed 's/^\(v[0-9]*\.[0-9]*\).*')
-bash: syntax error near unexpected token `)'
```

This is what I get without the regex:
```
$ sudo -E docker exec kube-master kubeadm version -o short
v1.9.0-alpha.2.852+cbdd18eee97369
```

**Comment by ivan4th** [comment]
The command fails because you have extra `)` at the end (it's from `$(...)` in dind-cluster.sh code)
```
docker exec kube-master kubeadm version -o short 2>/dev/null|sed 's/^\(v[0-9]*\.[0-9]*\).*'
```
The regex should work with your kubeadm version:
```
$ echo 'v1.9.0-alpha.2.852+cbdd18eee97369'|sed 's/^\(v[0-9]*\.[0-9]*\).*$/\1/'
v1.9
```
