### ISSUE TITLE
run kubeadm-dind-cluster behind a corporate proxy

### ISSUE THREAD

**Issue by stour** [kubernetes-sigs/kubeadm-dind-cluster#52]
I'm trying to run your awesome project behind a corporate proxy.

I first ran `$ ./dind-cluster-v1.8.sh up` to see what I get and it fails when trying to obtain `mirantis/kubeadm-dind-cluster` from Docker Hub. I didn't configured the proxy on my Docker daemon as I'm proxifying any call to Docker Hub through an internal Docker registry. So I updated the name of the images to obtain in `dind-cluster-v1.8.sh` with the prefix of my internal Docker registry.

I ran `$ ./dind-cluster-v1.8.sh up` another time. Pulling `mirantis/kubeadm-dind-cluster` worked. But then I got another issue:
```shell
...
Created symlink from /etc/systemd/system/multi-user.target.wants/kubelet.service to /lib/systemd/system/kubelet.service.
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.
unable to get URL "https://dl.k8s.io/release/stable-1.8.txt": Get https://dl.k8s.io/release/stable-1.8.txt: dial tcp 23.236.58.218:443: i/o timeout
```

More attempts to reach this URL follow and quite logically fail. So I have to exit the process manually at this stage.

**Do you have any idea what I have to configure in order to be able to run the cluster from behind a corporate proxy** (or if it was at least already tested) **?**

**Comment by wederbrand** [comment]
I too would like to run this behind a corporate proxy. My guess it that the proxy settings from the (original) host isn't moved copied down into the dind-hosts. 

I just starting playing with it today. I guess it would be possible to exec into the containers and fix the proxy settings and then try to restart the shell script. 

But it really would be nice to have start up options for a corporate (non transparent) proxy.
