### ISSUE TITLE
Add possibility for the local host to act as repository.

### ISSUE THREAD

**Issue by wederbrand** [kubernetes-sigs/kubeadm-dind-cluster#56]
Basically the goal is to replace minikube with this. Minikube is cpu and memory intensive and has only one master node and no workers.

The dind-approach is by far better, just not as mature.

On thing that doesn't work (or I found no way of doing it) is to build images locally without pushing them to any repository and the use them in the dind-cluster. 

That would be awesome.

**Comment by pigmej** [comment]
It's docker in docker so you may use:
`docker save {your_image} | docker exec -i {target_node} docker load`

where target_node is the node where you need your image (you can have script that does it automatically on all nodes)

**Comment by ivan4th** [comment]
Problem is that if you're using multiple nodes, you'll have to use some kind of docker repo, probably local one, and push images there. So are you asking about hints how to make DIND work with local docker image repository? Other possibility is to make a single-node cluster and use it's inner docker engine to build images etc. I can also give some hints how to do it if you want

**Comment by wrecklass** [comment]
I think what were looking for is a way to do:

`kubectl run myapp --image myapp:v3`

And have it pull the image from the local host system Docker repository, rather than Docker Hub.  Which wouldn't seem that hard to arrange. Minikube seems to manages to do this.

**Comment by wederbrand** [comment]
All I need to do i `docker build -t myapp:v3 .` and have it be accessible inside my cluster. 

Minikube solves by directing DOCKER_HOST to minikube's local repository. 

A single node DIND-cluster would work perfect, actually, running just the master, untainted, as in minikube would be a good-enough replacement for minikube (mainly what I'm after)

**Comment by prosegay** [comment]
I'm a kubernetes/kubeadm-dind newbie. I'm running multiple nodes on osx and this (docker build -t ...) doesn't work for me. when i run kubectl run --image foo it fails on can't find "library/foo" in the pod. I found dind::copy-image and it distributed the image, but still not able to find it.

**Comment by diafour** [comment]
It would be great to serve a registry from local `/var/lib/docker` but can't find such a solution.

So a simple workaround:

1. Run registry in docker on your host:
```
$ docker run -d -p 5000:5000 --restart=always --name registry registry:2
```

Now localhost:5000 is a registry url.

```
$ docker tag alpine:3.6 localhost:5000/alpine:3.6                                        
$ docker push localhost:5000/alpine:3.6     
...
3.6: digest: sha256:d6eda1410b93902ac84bdd775167c84ab59e5abadad88791d742fea93b161e93 size: 528
```

2. Run a proxy to forward each node's localhost:5000 to host's :5000 with a simple script:
```
  docker ps -a -q --filter=label=mirantis.kubeadm_dind_cluster | while read container_id; do
    docker exec ${container_id} /bin/bash -c "docker rm -fv registry-proxy || true"
    # run registry proxy: forward from localhost:5000 on each node to host:5000
    docker exec ${container_id} /bin/bash -c \
      "docker run --name registry-proxy -d -e LISTEN=':5000' -e TALK=\"\$(/sbin/ip route|awk '/default/ { print \$3 }'):5000\" -p 5000:5000 tecnativa/tcp-proxy"
  done
```
docs: https://hub.docker.com/r/tecnativa/tcp-proxy/

3. Test it:

```
$ kubectl run test --image=localhost:5000/alpine:3.6 -ti /bin/ash             
If you don't see a command prompt, try pressing enter.
/ #
```

The trick is that 127.0.0.0/8 network is in insecure registries by default. No need to init cluster with DIND_INSECURE_REGISTRIES variable and to edit /etc/docker/daemon.json.
