### ISSUE TITLE
Can not access to service on local host

### ISSUE THREAD

**Issue by lingxiankong** [kubernetes-sigs/kubeadm-dind-cluster#71]
I installed kubeadm-dind-cluster successfully on my local host using `dind-cluster-v1.8.sh up`, i created deployment and exposed a service. I can access that service inside master container, but failed on local. Can anybody help me please?

**Comment by savamilovanovic** [comment]
I was able to expose it using EXTRA_PORTS environment variable.

**Comment by riuvshin** [comment]
you want something like nodeport experience, but what you really want to do is to explore what ingress is.

**Comment by LingxianKong** [comment]
@savamilovanovic, hi, could you please describe in detail? thanks!

**Comment by LingxianKong** [comment]
@riuvshin with nodeport, do I need to expose service ports dynamically for k8s containers?

**Comment by savamilovanovic** [comment]
Assume you have a Cassandra cluster service on 30942 and you want to see it on the host, on port 9042:
```
export EXTRA_PORTS="9042:30942"
export NUM_NODES=1
dind-cluster-v1.8.sh up
docker ps 
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS              PORTS                               NAMES
6b8d19021dce        mirantis/kubeadm-dind-cluster:v1.8   "/sbin/dind_init s..."   20 hours ago        Up 20 hours         127.0.0.1:8080->8080/tcp            kube-master
7160196a291d        mirantis/kubeadm-dind-cluster:v1.8   "/sbin/dind_init s..."   20 hours ago        Up 20 hours         8080/tcp, 0.0.0.0:9042->30942/tcp   kube-node-1
```
You'll see that top level docker exposes cluster service port on 9042, for kube-node-1
```
PORTS                               NAMES
8080/tcp, 0.0.0.0:9042->30942/tcp   kube-node-1
```
To make it work with more than one node, some work on _dind-cluster-v1.8.sh_ would be needed.

**Comment by LingxianKong** [comment]
@savamilovanovic thanks for your reply.

But how I can specify EXTRA_PORTS for the services need to be created dynamically during k8s cluster running?

**Comment by savamilovanovic** [comment]
Perhaps using 
    kubectl port-forward
but, it didn't work for me for some reason. Might be related with permissions. It blocks shell saying _Forwarding from 127.0.0.1:9042 -> 9042_ but it didn't work when I tried to access the service.

```
sava@GF888SF2E:/mnt/c/Users/212485320$ sudo $HOME/.kubeadm-dind-cluster/kubectl port-forward cassandra-5dd7668596-vz52j 9042:9042
Forwarding from 127.0.0.1:9042 -> 9042 
```
I have to troubleshoot it yet. If you figure that out, or if it works for you, please let me know.

**Comment by LingxianKong** [comment]
port-forward command cannot be used for service, see here: https://github.com/kubernetes/kubernetes/issues/15180

**Comment by lukaszo** [comment]
The easiest way to access service is to use service type=NodePort
