### ISSUE TITLE
Error waiting for kube-proxy and the nodes

### ISSUE THREAD

**Issue by vs7098** [kubernetes-sigs/kubeadm-dind-cluster#72]
Hi There i am trying to build one dev machine  with 1.8, however its failing at kube-proxy.
Any help really appreciated.
 
# ./dind-cluster-v1.8.sh up

>WARNING: cluster glitch: proxy pods aren't removed; pods may 'blink' for some time after restore
NAME                         READY     STATUS        RESTARTS   AGE
etcd-kube-master             1/1       Running       0          17s
kube-dns-545bc4bfd4-vnq5z    2/3       Terminating   0          59s
kube-dns-855bdc94cb-gj8q9    0/3       Terminating   0          25s
kube-proxy-mfx66             0/1       Terminating   2          59s
kube-scheduler-kube-master   0/1       Pending       0          2s
>* Waiting for kube-proxy and the nodes
.......................................................................................................................................................................................................Error waiting for kube-proxy and the nodes

# kubectl get pods --all-namespaces
>NAMESPACE     NAME                                  READY     STATUS             RESTARTS   AGE
kube-system   etcd-kube-master                      1/1       Running            1          3m
kube-system   kube-apiserver-kube-master            1/1       Running            1          1m
kube-system   kube-controller-manager-kube-master   1/1       Running            1          1m
kube-system   kube-proxy-d7dlb                      0/1       CrashLoopBackOff   4          2m
kube-system   kube-proxy-gwdfl                      0/1       CrashLoopBackOff   4          2m
kube-system   kube-proxy-t49zz                      0/1       Error              4          1m
kube-system   kube-scheduler-kube-master            1/1       Running            1          3m

# kubectl logs **kube-proxy-t49zz** -n kube-system

>W0118 14:16:26.111384       1 server.go:191] WARNING: all flags other than --config, --write-config-to, and --cleanup are deprecated. Please begin using a config file ASAP.
time="2018-01-18T14:16:26Z" level=warning msg="Running modprobe ip_vs failed with message: ``, error: exec: \"modprobe\": executable file not found in $PATH"
W0118 14:16:26.123933       1 server_others.go:268] Flag proxy-mode="" unknown, assuming iptables proxy
I0118 14:16:26.126071       1 server_others.go:122] Using iptables Proxier.
W0118 14:16:26.134066       1 proxier.go:476] clusterCIDR not specified, unable to distinguish between internal and external traffic
I0118 14:16:26.134240       1 server_others.go:157] Tearing down inactive rules.
I0118 14:16:26.194376       1 conntrack.go:98] Set sysctl 'net/netfilter/nf_conntrack_max' to 131072
I0118 14:16:26.194605       1 conntrack.go:52] Setting nf_conntrack_max to 131072
I0118 14:16:26.201140       1 conntrack.go:83] Setting conntrack hashsize to 32768
error: write /sys/module/nf_conntrack/parameters/hashsize: operation not supported

**Comment by tallaxes** [comment]
It seems like this is due to mismatch of `wrapkubeadm` expectations regarding the `kube-proxy`'s ConfigMap key names. `wrapkubeadm` (in `dind::frob-proxy-configmap`) expects and attempts to patch `config.conf`, but it is now `kubeconfig.conf` (possibly due to `kubernetesVersion: v1.10.0` in kubeadm config?) Changing the name to `kubeconfig.conf` in `wrapkubeadm` appears to fix this.

**Comment by vs7098** [comment]
Still the same issue. 

I **did try with dind-cluster-v1.9.sh and dind-cluster-v1.8.sh both having issue, however with 1.7 i am able to build the cluster** 


>  kube-scheduler-kube-master
> 
>  0/1 Pending 0 2s
> 
> Waiting for kube-proxy and the nodes
> .......................................................................................................................................................................................................Error waiting for kube-proxy and the nodes

**Comment by tallaxes** [comment]
`wrapkubeadm` is part of the image. You tried with a custom image that included the latest `wrapkubeadm` plus the above fix? This seemed to work for me. Note that both `jsonpath` and `--from-file` need to fixed.

**Comment by DavidTPate** [comment]
@tallaxes any chance of the `wrapkubeadm` image being updated? Running into the same issue.

**Comment by tallaxes** [comment]
Sorry, that's outside of my control, would love to see updated images as well. @ivan4th ?

FWIW, if you have to have it now, but don't want to or can't rebuild the images from scratch locally, you can get the latest `wrapkubeadm`, fix it as described above, `chmod 755 wrapkubeadm`, replace it in a custom image with the following trivial Dockerfile, and have e.g. `dind-cluster-v1.8.sh`  use it (by specifying it as image and disabling the check for update). That's what I did to test the fix. Yes, I'd rather have an updated image too. ;-)

```
FROM mirantis/kubeadm-dind-cluster:v1.8
COPY wrapkubeadm /usr/local/bin/wrapkubeadm
```

**Comment by NRaoV** [comment]
Yes. It occurs when you change the port from 8080 to 8085
