### ISSUE TITLE
Exposing an External IP Address to Access an Application in a Cluster

### ISSUE THREAD

**Issue by savamilovanovic** [kubernetes-sigs/kubeadm-dind-cluster#74]
I successfully installed dind-cluster on my laptop using 1.8 sh. I then followed steps from k8s tutorial:
https://kubernetes.io/docs/tutorials/stateless-application/expose-external-ip-address/

It is possible to access the service from inside the cluster. 
However, external port never gets assigned, EXTERNAL-IP stays forever in _pending_:
```
sava@DellXPS:/mnt/c/k8s/helloworld$ kubectl get services my-service
NAME         TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
my-service   LoadBalancer   10.104.13.14   <pending>     8080:31339/TCP   21m
```
Could somebody give me a hint if / how would be possible to expose LoadBalancer service on the host with running kubeadm-dind-cluster? Could https://github.com/Mirantis/k8s-externalipcontroller be used?

**Comment by riuvshin** [comment]
for LB I think you have to try ingress

I actually trying to do something similar, I've created ingress for my service and now I have an endpoint:
```
kubectl get ingress --all-namespaces
NAMESPACE   NAME          HOSTS              ADDRESS      PORTS     AGE
che         my-ingress   127.0.0.1.nip.io   10.192.0.3   80        22m
```

but that endpoint `10.192.0.3` is not accessible from the the host :( 

if your external-ip is in pending state it probably means that there is nothing to handle that so `k8s-externalipcontroller` could help, give it a shot

**Comment by lukaszo** [comment]
The easiest way to access service is to use service type=NodePort
