### ISSUE TITLE
question: How to access ingress endpoint from the host?

### ISSUE THREAD

**Issue by riuvshin** [kubernetes-sigs/kubeadm-dind-cluster#78]
hi guys!
I need some help with accessing my app deployed to this dind cluster from the host...

my usecase is pretty simple, I have an app with a serivce + ingress
I used similar ingress configuration as in minikube with `--report-node-internal-ip-address`
and I see the endpoint IP but I can't reach it from the host. It perfectly works if I exec to che kube-node  container. I understand that internal IP is not supposed to be reachable from the host but how to expose it properly and make accessible?

**Comment by danielepolencic** [comment]
Same issue here.

**Comment by lukaszo** [comment]
Can you give an example of how are you deploying it? 

Using service with `type=NodePort` should work though.
