### ISSUE TITLE
localhost:8080/ui is USELESS

### ISSUE THREAD

**Issue by rbucker** [kubernetes-sigs/kubeadm-dind-cluster#80]
this configuration only means that you're running your cluster on a desktop with keyboard, mouse and monitor... and presumably a GUI with a browser.  However if you're like me you run everything experimental on a VPS whether it's next to my desktop or on amazon.  Therefore;

# k8s dashboard available at http://localhost:8080/ui

should really be the public IP and not localhost.

**Comment by pkrishn6** [comment]
I am running Dind cluster in a VM (using vagrant) and enabling portforwarding between the guest and host does not help either because k8s dashboard is bound to the loopback interface.

**Comment by FredericLeroy** [comment]
You can use kubectl or the dashboard by proxyfying it with the following command on the VM :

` /usr/bin/kubectl proxy --port 8080 --address <public_address> --accept-hosts='^.*$'`

But after, you'll be limited to expose your services to the world (see issue #72)

**Comment by zoobab** [comment]
I have used a socat process to listen on 0.0.0.0 and forward the port.

**Comment by charlesxucheng** [comment]
I tried the ssh command above but it does not work. Using nc works though. 

nc -l -p $localport -c "nc $remotehost $remoteport"

e.g.
nc -l -p 8081 -c "nc localhost 32768"

**Comment by sedlund** [comment]
nc is not encrypted and insecure.  if you use ssh as above, point your
browser to http://localhost:8080 -- if it does not work the VPS your using
might have the ssh daemon configured to not allow forwarding ports, enable
it in /etc/ssh/sshd_config or equivalent and reload ssh config -
/etc/init.d/ssh reload.   debug ssh connections by using -vvv as an option.
